---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('data.table')
library('ggplot2')
```

## R Markdown

```{r cars}
cloud_data <- fread("cloud-data.csv")
head(cloud_data)
```
## Summary Stats and EDA

```{r}
sapply(cloud_data, class)
summary(cloud_data)
```

## Including Plots

```{r pressure, echo=FALSE}
ggplot(data = cloud_data)+
  geom_point(aes(x = Ozone, y = Solar.R, color = Temp))+
  facet_grid(.~Month)
```

## Which are missing? missing at random?

```{r}
cloud_data[is.na(Solar.R), summary(.SD)]
cloud_data[is.na(Ozone), summary(.SD)]
```

## The best clouds!

clouds with the most solar radiation, deemed the best. Everyone likes radioactive clouds.
```{R}
cloud_data[order(Solar.R, decreasing = T)]
```

## who let the clouds out

```{r}
plot_dat <- melt(cloud_data[, .SD, .SDcols = -"Day"], id.vars = "Month")

ggplot(data = plot_dat)+
  geom_boxplot(aes(group = as.factor(Month), y = value,  fill = as.factor(Month)))+
  labs(y = "Temperature", title = "Boxplot of Temperature", fill = "Month")+
  theme(legend.position = "bottom") +
  facet_wrap(~variable, scale = "free")

```



